name: CI

on:
  pull_request:
    branches: [ test ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: executing remote ssh commands using ssh-private-key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd WEB13-JDevBook && git pull origin test
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd server && npm install && pm2 restart npm -- start
            cd ../client && npm install && npm run build
            sudo service nginx restart
